### PR TITLE
Add support for Linux PowerShell

### PR DESCRIPTION
**Pull request by Daniel15**
Fixes some Windows-isms so this extension works with the open-source cross-platform release of PowerShell too. Unfortunately script signing has not been implemented on any platforms other than Windows, and the `-ExecutionPolicy Bypass` parameter actually crashes PowerShell on non-Windows platforms (https://github.com/PowerShell/PowerShell/issues/2742). Because of this, we need to detect if the script is running on a non-Windows platform, and pass different command-line parameters

I tested with a simple script:
```powershell
Write-Output "Hello World!"
```

Example console output:
```
Started by user anonymous
Building remotely on Debian in workspace /opt/jenkins-slave/workspace/PowerShellLinux
[PowerShellLinux] $ powershell -NonInteractive "& '/tmp/hudson1244991839188540732.ps1'"
Hello World!
Finished: SUCCESS
```

I checked that it still works fine on a Windows master:
```
Started by user anonymous
Building on master in workspace C:\src\powershell-plugin\work\workspace\PowerShellWindows
[PowerShellWindows] $ powershell.exe -NonInteractive -ExecutionPolicy Bypass "& 'C:\Users\Daniel\AppData\Local\Temp\hudson2733142206807201603.ps1'"
Identity added: /home/Daniel/.ssh/id_rsa (/home/Daniel/.ssh/id_rsa)
Hello World!
Finished: SUCCESS
```

And a Windows slave:
```
Started by user anonymous
Building remotely on WinSlaveTest in workspace C:\temp\JenkinsSlaveTest\workspace\PowerShellWindows
[PowerShellWindows] $ powershell.exe -NonInteractive -ExecutionPolicy Bypass "& 'C:\Users\Daniel\AppData\Local\Temp\hudson5086970231154431648.ps1'"
Hello World!
Finished: SUCCESS
```

### CODE REVIEW

**Comment by Daniel15** [comment]
Could you please release a new version of the plugin containing this update?

**Comment by bhundven** [comment]
Any update on a release?
https://issues.jenkins-ci.org/browse/JENKINS-45832

**Comment by 88weighed** [comment]
A release would be nice. In the meantime I have tried a little workaround by renaming `/usr/bin/powershell `to `/usr/bin/powershell.exe`.

This has changed my console output drastically from not being able to run at all, to not finding the ps1 file.

**/usr/bin/powershell:**
`Building in workspace /var/lib/jenkins/workspace/Powershell-01
[Powershell-01] $ powershell.exe -NonInteractive -ExecutionPolicy ByPass "& '/tmp/jenkins8141295076279005189.ps1'"
FATAL: command execution failed
java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
Caused: java.io.IOException: Cannot run program "powershell.exe" (in directory "/var/lib/jenkins/workspace/Powershell-01"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at hudson.Proc$LocalProc.<init>(Proc.java:249)
	at hudson.Proc$LocalProc.<init>(Proc.java:218)
	at hudson.Launcher$LocalLauncher.launch(Launcher.java:930)
	at hudson.Launcher$ProcStarter.start(Launcher.java:450)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:109)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:66)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:736)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:496)
	at hudson.model.Run.execute(Run.java:1737)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:421)
Build step 'Windows PowerShell' marked build as failure
Finished: FAILURE`

**/usr/bin/powershell.exe:**
`Building in workspace /var/lib/jenkins/workspace/Powershell-01
[Powershell-01] $ powershell.exe -NonInteractive -ExecutionPolicy ByPass "& '/tmp/jenkins8691073571794626460.ps1'"
The argument '& '/tmp/jenkins8691073571794626460.ps1'' is not recognized as the name of a script file. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
Build step 'Windows PowerShell' marked build as failure
Finished: FAILURE`

**Comment by bakasmarius** [comment]
I agree, a release would be VERY useful. Is there any reason it can't be released, like... now?

**Comment by idoru78** [comment]
Will this need to be updated now that the executable has changed from "powershell" to "pwsh"?

**Comment by splatteredbits** [comment]
Can we get this released, please?

**Comment by shinpou** [comment]
It seems to have been merged already, but this solution doesn't work at all if you wish to run pwsh on Windows also, which you probably might want to do nowadays.

**Pull request merged**
