### PR TITLE
Added selection of preferred PowerShell version for Windows machines

### PR DESCRIPTION
**Pull request by PiotrBaran1010**
Similar functionality as in [https://github.com/jenkinsci/powershell-plugin/pull/15](https://github.com/jenkinsci/powershell-plugin/pull/15) but with changes suggested by @froque

Reference: [https://issues.jenkins-ci.org/browse/JENKINS-52421](https://issues.jenkins-ci.org/browse/JENKINS-52421)

### CODE REVIEW

**Comment by froque** [comment]
This a better PR than #15, but I'm afraid is still not what I was expecting. 

With this PR I can choose PowerShell Version Preference between "_Windows PowerShell_" and "_PowerShell Core_" in global jenkins configuration (http://localhost:8080/jenkins/configure) 
image

I was expecting to be able to configure each individual jenkins slave (http://localhost:8080/jenkins/computer/slave1/configure): 
image

**Comment by PiotrBaran1010** [comment]
Would it be ok to have one global setting that the slaves would inherit by default, with the option to override it for individual slaves? I have a pretty complex setup in which slaves are created and removed dynamically based on load and I wouldn't want to modify settings per slave in that case.

**Comment by froque** [comment]
> Would it be ok to have one global setting that the slaves would inherit by default, with the option to override it for individual slaves? 

yes, that makes sense

**Comment by PiotrBaran1010** [comment]
Hi, @froque
Pushed new changes according to your suggestions, please check. Thanks!

**Comment by marcohald** [comment]
Is there anything new to this PR ?
I would also need this

**Comment by BengalBrony** [comment]
> This a better PR than #15, but I'm afraid is still not what I was expecting.
> 
> With this PR I can choose PowerShell Version Preference between "_Windows PowerShell_" and "_PowerShell Core_" in global jenkins configuration (http://localhost:8080/jenkins/configure)
> image
> 
> I was expecting to be able to configure each individual jenkins slave (http://localhost:8080/jenkins/computer/slave1/configure):
> image

Has this been removed? I am not seeing it in Jenkins configuration page anymore. Perhaps because the path to the configure page has changed to http://localhost:8080/configure ? Because I am not seeing this I cannot run pwsh.exe for my powershell plugin and am forced to use Windows Powershell 5.1 instead of Powershell 7.1.

**Pull request merged**
