### PR TITLE
make pwsh work

### PR DESCRIPTION
**Pull request by onyxhat**

### CODE REVIEW

**Comment by onyxhat** [comment]
Suggesting a small change to the way the plugin constructs the call to pwsh as the original fails to be properly identified as a path to the ps1 script location.

**Comment by ViceIce** [comment]
I would prefer #12

**Comment by rkeithhill** [comment]
Agreed. PR #12 handles both powershell and pwsh.

**Comment by chrisalbrecht** [comment]
Closing in lieu of https://github.com/jenkinsci/powershell-plugin/pull/12

**Pull request closed without merging**
